#ifndef CONFIG_H
#define CONFIG_H

/* Define INDI Data Dir */
#cmakedefine INDI_DATA_DIR "@INDI_DATA_DIR@"
/* Define Driver version */
#define SKYWALKERFOCUSER_VERSION_MAJOR @SKYWALKERFOCUSER_VERSION_MAJOR@
#define SKYWALKERFOCUSER_VERSION_MINOR @SKYWALKERFOCUSER_VERSION_MINOR@

#endif // CONFIG_H
